In [ ]:
import numpy as np

# Creating Array

In [ ]:
#1-D Array

a=[1,2,3]
print(np.array(a))

[1 2 3]


In [ ]:
#2-D Array
a=[1,2,3]
b=[4,5,6]
c=[7,8,9]
print(np.array([a,b,c]))

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# 3-D Array
a=[1,2,3]
b=[4,5,6]
c=[7,8,9]
print(np.array([[a,b,c],[a,b,c],[a,b,c]]))

[[[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]

 [[1 2 3]
  [4 5 6]
  [7 8 9]]]


In [ ]:
# using fromiter
iterable= (i for i in range(6))
print(np.fromiter(iterable,int))

[0 1 2 3 4 5]


In [ ]:
#using empty

print(np.empty([3,3],int))

# Initial Placeholders

In [ ]:
# using arange
print(np.arange(10))
print(np.arange(9).reshape(3,3))
print(np.arange(18).reshape(2,3,3))

[0 1 2 3 4 5 6 7 8 9]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]]


In [ ]:
#using linspace
print(np.linspace(1,10,2))

In [ ]:
#using zeros
print(np.zeros([3,3],int))

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [ ]:
#using ones
print(np.ones([3,3],int))

In [ ]:
import numpy as np
a = np.zeros((2, 3, 4))
print(a)

In [ ]:
#using random.randint
print(np.random.randint(1,10,[2,3,3]))

[[[6 4 4]
  [5 7 5]
  [2 4 9]]

 [[4 3 9]
  [3 4 3]
  [7 9 7]]]


In [ ]:
#using random.rand
print(np.random.rand(3,3))

[[0.17519175 0.22962459 0.75962841]
 [0.48570648 0.93461425 0.91989509]
 [0.80529574 0.60856608 0.09173164]]


In [ ]:
#using full with "value"
print(np.full([3,3],5))

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [ ]:
#using eye for identity matrix
print(np.eye(3))

# Saving and Loading File

In [ ]:
# Saving and loading on Disk
np.save('test', np.zeros(5))

a = np.load('test.npy')
print(a)

In [ ]:
# Saving in text file and loading from text file

x = np.arange(5)
np.savetxt("myfile.txt", x, delimiter =', ')

d = np.loadtxt("myfile.txt")
print(d)

In [ ]:
#Loading a CSV file  # required to add csv file
Data = np.genfromtxt("myfile.csv", delimiter=",")
print(Data)


# Sorting Array

In [ ]:
#1-D sorting

a = np.array([12, 15, 10, 1])
print(np.sort(a))

In [ ]:
# 2-D Sorting

a = np.array(
    [[12, 15],
    [10, 1]])
print([a])


[array([[12, 15],
       [10,  1]])]


In [ ]:
print(np.sort(a, axis=0)) # sorting with row

[[10  1]
 [12 15]]


In [ ]:
print(np.sort(a, axis=-1)) # sorting with column

[[12 15]
 [ 1 10]]


In [ ]:
print(np.sort(a)) # sorting with row( by default)

# NumPy Array Manipulation

In [ ]:
a=np.append([1,2,3],[4])
print(a)

[1 2 3 4]


In [ ]:
a=np.append([[1,2,3],[4,5,6]],[[7],[8]],axis=1)
print(a)

[[1 2 3 7]
 [4 5 6 8]]


In [ ]:
# append array item in 1-D
a=np.array([1,2,3])
#print(np.append(a,[4]))

# append array item in 2-D
b=np.array([[1,2,3],[4,5,6]])
print(b)

print(np.append(b,[[7,8,9]],axis=0)) # 0 axis meanse row
print(np.append(b,[[7],[8]],axis=1)) # 1 axis meanse column



In [ ]:
# Insert an element at a particular index of a 1D array

arr = np.array([10, 20, 30])
print(np.insert(arr, 1, 99))

#Insert into 2D array at a given index
arr1 = np.array([[1, 2],[3, 4]])

print(np.insert(arr1, 1, [9,3], axis=1))
print(np.insert(arr1, 1, [9,3], axis=0))

In [ ]:
#Delete an element from 1D array
arr = np.array([1, 2, 3, 4])
print(np.delete(arr, 2))

#Delete from 2D array
arr1 = np.array([[1, 2],[3, 4]])

print(arr1)
print(np.delete(arr1, 1, axis=1)) # 0---> row, 1---->column

In [ ]:
#Reshape 1D → 2D
arr = np.arange(12)
print(np.reshape(arr, (3, 4)))

#Reshape 2D → 1D
arr = np.array([[1, 2, 3],[4, 5, 6]])
print(arr.reshape(6))


In [ ]:
#Resize array
arr = np.array([1, 2, 3, 4])
arr.resize(3, 4)
print(arr)

In [ ]:
#Flatten array (convert 2D → 1D)
arr = np.array([[1, 2],[3, 4]])
print(arr.flatten())

# Combining and Splitting Commands

In [ ]:
arr1 = np.array([[1, 2],[3, 4]])
arr2 = np.array([[5, 6],[7, 8]])

#Combine row-wise → axis=0
print(np.concatenate((arr1, arr2), axis=0))

#Combine column-wise → axis=1
print(np.concatenate((arr1, arr2), axis=1))

#Combine into 1D array → axis=None
print(np.concatenate((arr1, arr2), axis=None))

#Using np.stack() (adds a new dimension)
print(np.stack((arr1, arr2), axis=1))


In [ ]:
a = np.arange(9).reshape(3, 3)

#Split horizontally (by columns) → axis=1
print(np.split(a, 3, axis=1))  #Using np.hsplit(a,3) (horizontal split shortcut)

#Split vertically (by rows) → axis=0
print(np.split(a, 3, axis=0))  #Using np.vsplit(a,3) (vertical split shortcut)

# Indexing, Slicing and Subsetting

In [2]:
# indexing integer
import numpy as np
a = np.array([[1, 2],
              [3, 4],
              [5, 6]])

print(a[[0, 1, 2], [0, 0, 1]])  #(0,0) → 1, (1,0) → 3, (2,1) → 6

# Boolean Indexing
a = np.array([10, 40, 80, 50, 100])
print(a[a > 50])

[1 3 6]
[ 80 100]


In [3]:
#Slicing
a = np.array([1, 2, 3, 4, 7])
print(a[1:])

[2 3 4 7]


In [4]:
#Subsetting

arr = np.array([1, 2, 3, 4, 7])

print("Original:", arr)
print("Subsetting:", arr[np.array([1, 3, -3])])

Original: [1 2 3 4 7]
Subsetting: [2 4 3]


# Copying and Viewing Arrays

In [ ]:
#Normal Assignment (=) → Same reference
#both point to same array

arr = np.array([1, 2, 3, 4])
nc = arr   # no new memory created

print("IDs same?", id(arr) == id(nc))

nc[0] = 12
print("Original:", arr)
print("Assigned:", nc)


IDs same? True
Original: [12  2  3  4]
Assigned: [12  2  3  4]


In [ ]:
#Deep Copy (.copy()) → New memory
#changing original does not affect copy
arr = np.array([1, 2, 3, 4])
c = arr.copy()

print("IDs same?", id(arr) == id(c))

#arr[0] = 12
c[0]=12
print("Original:", arr)
print("Copy    :", c)


IDs same? False
Original: [1 2 3 4]
Copy    : [12  2  3  4]


In [ ]:
#View (.view()) → Different object, same data
#different IDs, but changes reflect in both because they share data

arr = np.array([1, 2, 3, 4])
v = arr.view()

print("IDs same?", id(arr) == id(v))

arr[0] = 12
print("Original:", arr)
print("View    :", v)


# Inspecting Properties

In [ ]:
a = np.array([[1, 2, 3],[4, 5, 6]])

b = np.array([1.2, 3.5, 5.8])

e = np.array([10, 20, 30, 40])

print(a.shape) # Array dimensions (rows, columns)
print(len(a)) #Length of array
print(b.ndim) #Number of array dimensions
print(e.size) #Number of array elements
print(b.dtype) #Data type of array elements
print(b.dtype.name) #same but just the name as a string.
print(b.astype(int))#Convert to different data type
print(a.itemsize) #Size of each array element in bytes



# NumPy Array Mathematics

In [ ]:
#Arithmetic Operations
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[3, 2, 1],
              [1, 2, 3]])

np.subtract(a,b)
np.add(a,b)
np.divide(a,b)
np.multiply(a,b)
np.exp(b)
np.sqrt(b)
np.sin(a)
np.cos(b)
np.log(a)



array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [ ]:
#Comparison Operations
print(a == b)      # elementwise equal
print(a < 2)       # elementwise less than 2
print(np.array_equal(a,b))  # check whole array equality

[[False  True False]
 [False False False]]
[[ True False False]
 [False False False]]
False


In [ ]:
#Aggregate Functions

a = np.array([[1, 2, 3],
              [4, 5, 6]])
b = np.array([[3, 2, 1],
              [1, 2, 3]])


a.sum()
a.min()
b.max(axis=0)
b.cumsum(axis=1)
a.mean()
np.median(b)
np.corrcoef(a.flatten(), b.flatten())
np.std(b)




np.float64(0.816496580927726)